export const SIGNING_IN = 'SIGNING_IN';
export const ADDING_USER = 'ADDING_USER';
export const USER_ADDED = 'USER_ADDED';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_IN_ERR = 'SIGN_IN_ERR';
export const CREATING_USER_ERR = 'CREATING_USER_ERR';
export const ADD_ROLES = 'ADD_ROLES';
export const ADDING_TEACHERS = 'ADDING_TEACHERS';
export const ADD_TEACHERS = 'ADD_TEACHERS';
export const ADDING_TEACHERS_ERR = 'ADDING_TEACHERS_ERR';
export const ADD_STUDENTS = 'ADD_STUDENTS';
export const ADDING_STUDENTS = 'ADDING_STUDENTS';
export const ADDING_STUDENTS_ERR = 'ADDING_STUDENTS_ERR';
export const ADDING_SUBJECT = 'ADDING_SUBJECT';
export const SUBJECT_ADDED = 'SUBJECT_ADDED';
export const ADDING_SUBJECT_ERR = 'ADDING_SUBJECT_ERR';
export const ADDING_SUBJECTS = 'ADDING_SUBJECTS';
export const ADDING_SUBJECTS_ERR = 'ADDING_SUBJECTS_ERR';
export const ADD_SUBJECTS = 'ADD_SUBJECTS';
export const ADDING_GROUP = 'ADDING_GROUP';
export const GROUP_ADDED = 'GROUP_ADDED';
export const ADDING_GROUP_ERR = 'ADDING_GROUP_ERR';
export const ADD_GROUPS = 'ADD_GROUPS';
export const ADDING_GROUPS = 'ADDING_GROUPS';
export const ADDING_GROUPS_ERR = 'ADDING_GROUPS_ERR';

export const ADDING_SCHEDULE_ERR = 'ADDING_SCHEDULE_ERR';
export const ADDING_SCHEDULE = 'ADDING_SCHEDULE';
export const SCHEDULE_ADDED = 'SCHEDULE_ADDED';

export const ADDING_SCHEDULES = 'ADDING_SCHEDULES';
export const ADD_SCHEDULES = 'ADD_SCHEDULES';
export const ADDING_SCHEDULES_ERR = 'ADDING_SCHEDULES_ERR';

export const ADDING_AUDIENCES = 'ADDING_AUDIENCES';
export const ADD_AUDIENCES = 'ADD_AUDIENCES';
export const ADDING_AUDIENCES_ERR = 'ADDING_AUDIENCES_ERR';
